image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - build-base
  - hugo
  - hut
secrets:
  - ca99d209-296a-41b7-9eda-454250e4b901
environment:
  REPO: CoreForth-0
  SITE: ekoeppen.srht.site
sources:
  - https://git.sr.ht/~ekoeppen/build-scripts
artifacts:
  - docs.tar.gz
tasks:
  - docs: |
      cd $REPO/docs
      ./mkmd.sh
      hugo build
      tar -cz -f $HOME/docs.tar.gz -C public .
      hut pages publish -d $SITE -s coreforth-0 $HOME/docs.tar.gz 
  - mirror-to-github: ./build-scripts/github-mirror $REPO
